### ISSUE TITLE
Is this repo the one in arxiv 1911.06667?

### ISSUE THREAD

**Issue by SkeletonOne** [CaoWGG/Mask-CenterNet#1]

**Comment by CaoWGG** [comment]
@SkeletonOne 
No!
This is an instance segmentation algorithm based on **CenterNet**. 
Just an experiment.

**Comment by CaoWGG** [comment]
@SkeletonOne 
I have changed the repo name.

**Comment by SkeletonOne** [comment]
@CaoWGG Got it!
Will this work be reported on arxiv or somewhere else in the future?
