### ISSUE TITLE
Model Release

### ISSUE THREAD

**Issue by JialianW** [CaoWGG/Mask-CenterNet#12]
Hi there author,

Thanks for your awesome work of combining CenterNet and CondInst. Can you release the trained model? Such that we can more easily use this work.

**Comment by BloodLemonS** [comment]
> Hi there author,
> 
> Thanks for your awesome work of combining CenterNet and CondInst. Can you release the trained model? Such that we can more easily use this work.

Have you got the weights? Can we share it?
