### ISSUE TITLE
`ransform_segs` in the `utils.image` did not upload to the repo.

### ISSUE THREAD

**Issue by tensorboy** [CaoWGG/Mask-CenterNet#3]
Hi @CaoWGG 

Thanks for your great work!

Here needs the import of `transform_segs`: https://github.com/CaoWGG/Mask-CenterNet/search?q=transform_segs&unscoped_q=transform_segs

However, it did not upload to this repo. :)

**Comment by CaoWGG** [comment]
@tensorboy 
You can delete it.

**Comment by CaoWGG** [comment]
@tensorboy 
Did you run it successfully?

**Comment by tensorboy** [comment]
Hi Cao,

I will run it tmr and happy thanksgiving day. :)

**Comment by tensorboy** [comment]
Hi @CaoWGG 

The training begins now, and the loss converges pretty well, thanks!
